
name : A Basic Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  mainjob:
    name: "print variables"
    runs-on: ubuntu-latest
    env: 
      MY_SEC: ${{secrets.MY_TOP_SEC}}
    steps:
      - run: |
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ENV"
          echo "$GITHUB_PATH"
          echo "$GITHUB_JOB"
          echo "$GITHUB_RUN_ID"
          echo "$GITHUB_RUN_NUMBER"
          echo "$RUNNER_NAME"
          echo "MY SECRET: ${{ secrets.MY_TOP_SEC }}"
          echo "MY env sec is : $MY_SEC"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Checked out the code"

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script"
          echo "It can run multiple commands"
          echo "Like this one"

  build-dbs:
    runs-on: windows-latest
    steps:
      - run: echo "building api"

  build-db:
    needs: build
    runs-on: windows-latest
    steps:
      - run: echo "hello windows"

  package:
    needs: [build, build-db]
    runs-on: macos-latest

    steps:
      - run: echo "hello macos"